output:	bunceMatthewMain.o	bunceMatthewFunctionsLab1.o
	gcc	-Wall	bunceMatthewMain.o	bunceMatthewFunctionsLab1.o	-o	output
bunceMatthewMain.o:	bunceMatthewMain.c	bunceMatthewHeaderLab1.h
	gcc	-Wall	-c	bunceMatthewMain.c
bunceMatthewFunctionsLab1.o:	bunceMatthewFunctionsLab1.c	bunceMatthewHeaderLab1.h
	gcc	-Wall	-c	bunceMatthewFunctionsLab1.c

