output:	main.o	addNodeToList.o	countStopWords.o	createTweet.o	deleteTweet.o	displayTweets.o	loadTweetsFromFile.o	saveTweetsToFile.o	searchTweetsByKeyword.o	tokenCompare.o
	gcc	-Wall	-std=c99	main.o	addNodeToList.o	countStopWords.o	createTweet.o	deleteTweet.o	displayTweets.o	loadTweetsFromFile.o	saveTweetsToFile.o	searchTweetsByKeyword.o	tokenCompare.o	-o	output
main.o:	main.c	headerA3.h
	gcc	-Wall	-std=c99	-c	main.c
addNodeToList.o:	addNodeToList.c	headerA3.h
	gcc	-Wall	-std=c99	-c	addNodeToList.c
countStopWords.o:	countStopWords.c	headerA3.h
	gcc	-Wall	-std=c99	-c	countStopWords.c
createTweet.o:	createTweet.c	headerA3.h
	gcc	-Wall	-std=c99	-c	createTweet.c
deleteTweet.o:	deleteTweet.c	headerA3.h
	gcc	-Wall	-std=c99	-c	deleteTweet.c
displayTweets.o:	displayTweets.c	headerA3.h
	gcc	-Wall	-std=c99	-c	displayTweets.c
loadTweetsFromFile.o:	loadTweetsFromFile.c	headerA3.h
	gcc	-Wall	-std=c99	-c	loadTweetsFromFile.c
saveTweetsToFile.o:	saveTweetsToFile.c	headerA3.h
	gcc	-Wall	-std=c99	-c	saveTweetsToFile.c
searchTweetsByKeyword.o:	searchTweetsByKeyword.c	headerA3.h
	gcc	-Wall	-std=c99	-c	searchTweetsByKeyword.c
tokenCompare.o:	tokenCompare.c	headerA3.h
	gcc	-Wall	-std=c99	-c	tokenCompare.c
clean:
	rm *.o	output
